<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<AssemblyTitle>Estragonia</AssemblyTitle>

		<!-- Framework/Language -->
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>disable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<AnalysisMode>Recommended</AnalysisMode>
		<IsAotCompatible>true</IsAotCompatible>

		<!-- Package -->
		<IsPackable>true</IsPackable>
		<PackageReadmeFile>readme.md</PackageReadmeFile>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PublishRepositoryUrl>true</PublishRepositoryUrl>
		<PackageProjectUrl>https://github.com/MrJul/Estragonia</PackageProjectUrl>
		<PackageReleaseNotes>https://github.com/MrJul/Estragonia/releases</PackageReleaseNotes>
		<Description>Estragonia is a bridge allowing the use of the Avalonia UI framework in the Godot game engine.</Description>
		<PackageTags>avalonia;godot;ui;game</PackageTags>

		<!-- Source Link -->
		<IncludeSymbols>true</IncludeSymbols>
		<EmbedUntrackedSources>true</EmbedUntrackedSources>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>

		<!-- Access Avalonia internal/private APIs needed for platform backend implementation -->
		<AvaloniaAccessUnstablePrivateApis>true</AvaloniaAccessUnstablePrivateApis>
		<Avalonia_I_Want_To_Use_Private_Apis_In_Nuget_Package_And_Promise_To_Pin_The_Exact_Avalonia_Version_In_Package_Dependency>true</Avalonia_I_Want_To_Use_Private_Apis_In_Nuget_Package_And_Promise_To_Pin_The_Exact_Avalonia_Version_In_Package_Dependency>

	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="GodotSharp" Version="4.6.1" />
		<PackageReference Include="Avalonia" Version="12.*" />
		<PackageReference Include="Avalonia.Skia" Version="12.*" />
		<PackageReference Include="Avalonia.HarfBuzz" Version="12.*" />
		<PackageReference Include="Microsoft.SourceLink.GitHub" Version="1.1.1" PrivateAssets="all" />
	</ItemGroup>

	<ItemGroup>
		<None Include="../../readme.md" Pack="true" PackagePath="/" Visible="false" />
	</ItemGroup>

</Project>
